### ISSUE TITLE
uproot not imported if it is not installed (Dockerfile)

### ISSUE THREAD

**Issue by imtrigger** [callum-mccracken/M11_GRIDS#1]
Uproot module is not installed so it cannot be imported. Dockerfile should probably try to install it in the container environment?

itrigger@IsabelMacBook-2 ~ % docker exec -it efe25c6d2b58edc0b21e0806d521d271ce9934749476c7daef4df4266fc0c813 /bin/sh
# which root
# python --version
Python 3.9.12
# python beam_momentum.py -f output_000519.root
Traceback (most recent call last):
  File "/code/beam_momentum.py", line 11, in <module>
    import uproot
ModuleNotFoundError: No module named 'uproot'
# 

Try explicitly:
# python -c "import uproot"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'uproot'
# 

So install it:
pip install uproot
Collecting uproot
  Downloading uproot-4.3.4-py2.py3-none-any.whl (302 kB)
     |████████████████████████████████| 302 kB 3.2 MB/s 
Requirement already satisfied: setuptools in /opt/conda/lib/python3.9/site-packages (from uproot) (61.2.0)
Collecting numpy
  Downloading numpy-1.23.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (17.1 MB)
     |████████████████████████████████| 17.1 MB 28.6 MB/s 
Installing collected packages: numpy, uproot
Successfully installed numpy-1.23.2 uproot-4.3.4
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
# python beam_momentum.py -f output_000519.root
Traceback (most recent call last):
  File "/code/beam_momentum.py", line 13, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'

So do that too:
# pip install matplotlib
Collecting matplotlib
  Downloading matplotlib-3.5.3-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.whl (11.2 MB)
     |████████████████████████████████| 11.2 MB 3.2 MB/s 
Collecting cycler>=0.10
  Downloading cycler-0.11.0-py3-none-any.whl (6.4 kB)
Collecting pillow>=6.2.0
  Downloading Pillow-9.2.0-cp39-cp39-manylinux_2_28_x86_64.whl (3.2 MB)
     |████████████████████████████████| 3.2 MB 35.0 MB/s 
Collecting fonttools>=4.22.0
  Downloading fonttools-4.36.0-py3-none-any.whl (950 kB)
     |████████████████████████████████| 950 kB 23.7 MB/s 
Requirement already satisfied: numpy>=1.17 in /opt/conda/lib/python3.9/site-packages (from matplotlib) (1.23.2)
Collecting kiwisolver>=1.0.1
  Downloading kiwisolver-1.4.4-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.6 MB)
     |████████████████████████████████| 1.6 MB 31.9 MB/s 
Collecting pyparsing>=2.2.1
  Downloading pyparsing-3.0.9-py3-none-any.whl (98 kB)
     |████████████████████████████████| 98 kB 9.5 MB/s 
Collecting packaging>=20.0
  Downloading packaging-21.3-py3-none-any.whl (40 kB)
     |████████████████████████████████| 40 kB 6.4 MB/s 
Collecting python-dateutil>=2.7
  Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
     |████████████████████████████████| 247 kB 26.5 MB/s 
Collecting six>=1.5
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: six, pyparsing, python-dateutil, pillow, packaging, kiwisolver, fonttools, cycler, matplotlib
Successfully installed cycler-0.11.0 fonttools-4.36.0 kiwisolver-1.4.4 matplotlib-3.5.3 packaging-21.3 pillow-9.2.0 pyparsing-3.0.9 python-dateutil-2.8.2 six-1.16.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

# python beam_momentum.py -f output_000519.root
Traceback (most recent call last):
  File "/code/beam_momentum.py", line 15, in <module>
    from scipy.optimize import curve_fit
ModuleNotFoundError: No module named 'scipy'

so pip install scipy too... and now it works:
# python beam_momentum.py -f output_000519.root
opening file, reorganizing data
fitting curves, making histogram
calculating offset
calculating expected ToF
Calculated beam momentum: 109.0 MeV/c

**Comment by callum-mccracken** [comment]
Hmm strange, the Dockerfile should already install uproot and verify installation... Also the python version suggests to me you're not actually in the container...

Can you tell me the list of commands you used to try to run this?

My suggested list:

git clone git@github.com:callum-mccracken/M11_GRIDS.git
cd M11_GRIDS
docker build . -t m11
docker run -it m11
python beam_momentum.py -f output_000519.root

**Comment by imtrigger** [comment]
Yes, that is exactly what I did. But the line:
python -c "import uproot"
does not work (Mac - Monterey, uproot not installed locally, don't know if that matters) so I had to do:
pip install uproot
pip install matplotlib
pip install script
to get all the requirements installed before they could be imported.

**Comment by imtrigger** [comment]
(inside the container environment)
I didn't install them on the Mac.

**Comment by callum-mccracken** [comment]
Strange, if the docker image built properly up to that point (would it be possible to get everything printed to your screen while building?), that means it's running this line:

RUN conda create -y --name grids -c conda-forge --file requirements.txt

Which should install all the packages in requirements.txt (including uproot)...

I might try to make a mac virtual machine and see if I can reproduce this error

**Comment by imtrigger** [comment]
All right, bug report can be closed. I have absolutely no idea what changed between when I built the image 2 months ago (3.25 GB) which did not properly install the requirements, and the one today (3.3 GB), which apparently did,  but it works fine now.

**Comment by callum-mccracken** [comment]
Haha okay computers can be mysterious beasts, thanks for letting me know you had the issue anyway :)
